### ISSUE TITLE
Step1 Bricked ls-wxl

### ISSUE THREAD

**Issue by C007dudz** [rogers0/OpenLinkstation#11]
Hi

I did step1 after I have access to SSH in my LS-WXL, changed the password and everything else in default, ran the 1_debootstrap/build_rootfs_with_buffalo-kernel.sh script. After completion, issued the reboot command, then my nas box had a reboot loop. Not sure what I am missing here. Is there something that I should do before doing the reboot?

Also, do you have step by step instructions on how to do the details on the NEWS part?

**Comment by C007dudz** [comment]
Also, is there any instruction on how to do the details in the NEWS part?

**Comment by rogers0** [comment]
What version did you use?
I updated the script 3 weeks ago, which should fix the problem you described.
If it still happen with my latest code, I need to reproduce it in my environment.

About daily debian installer, I think the simple step is already included in the NEWS part.
Simply copy the 2 image to the 1st partition of your Linkstation and reboot, then you need to ssh to finish the real installation.

If you meet any problem, just let me know.
