### ISSUE TITLE
Error when doing step 1

### ISSUE THREAD

**Issue by qakcn** [rogers0/OpenLinkstation#12]
An error occured when doing step 1:

    E: Failed to mount /proc: Device or resource busy

How to solve this?

Thanks for your brilliant works.

**Comment by rogers0** [comment]
@qakcn please provide your stock firmware version and linkstation model name. thank you!

**Comment by qakcn** [comment]
LS-WXL with firmware version 1.71.

**Comment by rogers0** [comment]
@qakcn 
I tested 1.71 on LS-WXL a few months ago, without any problem.
I guess you ran the script, and meet something so interrupted it (such as Ctrl-C), then ran the script again.
If it's the case, I suggest you to reboot once, then try it again. If your reboot fails, you need to restore the stock firmware.
Please pay attention to you data. I don't guarantee the data would be always safe. Please backup your data before doing anything.

**Comment by qakcn** [comment]
Thank you, I'll try again.

**Comment by qakcn** [comment]
Did it again and succeeded.

But one more question. I found that blstools did not work. How can I make LED and fan work correctly?

**Comment by rogers0** [comment]
@qakcn 
currently no perfect support yet, but there're a few discussion here: #5 
closing this ticket because main issue resolved.
