### ISSUE TITLE
Step 2 brick my NAS LS-WXL...

### ISSUE THREAD

**Issue by door999mo** [rogers0/OpenLinkstation#6]
What I did..
I mounted /dev/md2 (I still don't know what where is root dev...)

root@LS-Jessie:/dev# mount /dev/md2 /mnt

and then go to the mnt where the script is located.
root@LS-Jessie:/mnt/OpenLinkstation

after that i ran the script for step 2...
root@LS-Jessie:/mnt/OpenLinkstation# 1_debootstrap/build_rootfs_with_buffalo-kernel.sh debian
3rd stage: Build Debian rootfs on final target device
STAGE=2 ARRAY=1 TARGET=/mnt TARGET_DEVICE=/dev/md2 BOOT_DEVICE=/dev/md0 rootfs=/dev/md2 bootfs=/dev/md0
BUFFALO_KERNEL=0 MACHINE_ID='Buffalo Linkstation LS-WXL/WSXL' DEB_KERNEL=
mkdir old_fs_backup
mv .* * old_fs_backup/
mv: cannot move ‘.’ to ‘old_fs_backup/.’: Device or resource busy
mv: cannot remove ‘..’: Is a directory
mv: cannot move ‘boot’ to ‘old_fs_backup/boot’: Device or resource busy
mv: cannot move ‘dev’ to ‘old_fs_backup/dev’: Device or resource busy
mv: cannot move ‘mnt’ to ‘old_fs_backup/mnt’: Device or resource busy
mv: cannot move ‘old_fs_backup’ to a subdirectory of itself, ‘old_fs_backup/old_fs_backup’
mv: cannot move ‘proc’ to ‘old_fs_backup/proc’: Device or resource busy
mv: cannot move ‘run’ to ‘old_fs_backup/run’: Device or resource busy
mv: cannot move ‘sys’ to ‘old_fs_backup/sys’: Device or resource busy
tar xf /rootfs.tar
1_debootstrap/build_rootfs_with_buffalo-kernel.sh: line 249: tar: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 144: blkid: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 144: blkid: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 144: blkid: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 160: /mnt/etc/fstab: No such file or directory
/mnt/OpenLinkstation/lib/shell_lib: line 361: mount: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 362: chroot: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 363: chroot: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 364: chroot: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 365: chroot: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 365: chroot: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 365: chroot: command not found
1_debootstrap/build_rootfs_with_buffalo-kernel.sh: line 254: chroot: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 144: blkid: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 140: blkid: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 144: blkid: command not found
1_debootstrap/build_rootfs_with_buffalo-kernel.sh: line 257: /mnt//etc/initramfs-tools/modules: No such file or directory
/mnt/OpenLinkstation/lib/shell_lib: line 144: blkid: command not found
1_debootstrap/build_rootfs_with_buffalo-kernel.sh: line 259: chroot: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 373: chroot: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 374: chroot: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 375: chroot: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 376: chroot: command not found
/mnt/OpenLinkstation/lib/shell_lib: line 377: chroot: command not found
1_debootstrap/build_rootfs_with_buffalo-kernel.sh: line 268: mount: command not found

It moved my /bin and some other folders which bricked my NAS...
root@LS-Jessie:/# cd
boot/          dev/           mnt/           old_fs_backup/ proc/          run/           sys/
root@LS-Jessie:/mnt/OpenLinkstation# ls
-bash: /bin/ls: No such file or directory
root@LS-Jessie:/mnt/old_fs_backup# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
root@LS-Jessie:/mnt/old_fs_backup# which ls
-bash: which: command not found
root@LS-Jessie:/old_fs_backup# cp -r * /
-bash: cp: command not found

Can anyone tell me how can i recover it...
Very much appreciated...

**Comment by door999mo** [comment]
In case someone as dumb as me...
Here is how to fix it..

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
export LD_LIBRARY_PATH=/old_fs_backup/lib:/old_fs_backup/lib/arm-linux-gnueabi

**Comment by door999mo** [comment]
Just figured out... it should be /dev/md1 for LS-WXL

**Comment by luckydevil13** [comment]
how to debrick NAS? if I have reboot loop :(

**Comment by door999mo** [comment]
You will need to move all your files from '/old_fs_backup' back to '/'

**Comment by rogers0** [comment]
I just fixed the issue, caused by read-only mount of /boot.
Please try the latest version from master branch. Sorry about the trouble and thank you for your patience!

**Comment by LPTT** [comment]
Hi,have the same problem as post 1. Now the wxl is stuck in a boot loop. How do I access the hdd to copy the old file system back? If i put one of the drives in my pc I cannot access it because it is a "raid member". Do I have to "kill" the raid?

**Comment by rogers0** [comment]
Dear LPTT,

I guess you didn't use the updated/latest code from github?

You can attach your 2 HDDs to your PC directly or via USB-SATA adapter, then command:
# mdadm -A /dev/md0 /dev/sdX1 /dev/sdY1
# mount /dev/md0 /mnt

Try to rename /mnt/uImage.flash-kernel.bak and /mnt/initrd.flash-kernel.bak to remove the ".bak", and then

# umount /mnt
# mdadm -S /dev/md0

pull the HDDs back to your Linkstation and reboot it.

If you don't have environment to attach both of your HDDs, you can also attach one HDD of your RAID-1 array, that would make a bit difficult, but still possible to rescue from technical view.

Hope this helps.

**Comment by LPTT** [comment]
Hi rogers0,
thanks for your quick answer. I did like you described and renamed uImage.flash-kernel.bak to uImage.flash-kernel and initrd.flash-kernel.bak to initrd.flash-kernel but it is still stuck in boot loop.

**Comment by rogers0** [comment]
I have some comment on Issue#11, which also applies to your problem.
- https://github.com/rogers0/OpenLinkstation/issues/11

**Comment by LPTT** [comment]
Thanks that actually helped. Now the debian installer gives me an error. Do you know this error by any chance?
Mar 23 19:03:52 net-retriever: gpgv: Signature made Wed Mar 23 15:18:43 2016 UTC using RSA key ID 2B90D010
Mar 23 19:03:52 net-retriever: 
Mar 23 19:03:52 net-retriever: gpgv: Good signature from "Debian Archive Automatic Signing Key (8/jessie) <ftpmaster@debian.org>"
Mar 23 19:03:52 net-retriever: 
**Mar 23 19:03:54 net-retriever: error: main/debian-installer/binary-armel/Packages.xz not found in /tmp/net-retriever-1361-Release (for SHA1 checksum).**
Mar 23 19:03:56 anna[1357]: WARNING **: bad d-i Packages file
Mar 23 19:03:58 net-retriever: gpgv: Signature made Wed Mar 23 15:18:43 2016 UTC using RSA key ID 46925553
Mar 23 19:03:58 net-retriever: 
Mar 23 19:03:58 net-retriever: gpgv: Good signature from "Debian Archive Automatic Signing Key (7.0/wheezy) <ftpmaster@debian.org>"
Mar 23 19:03:58 net-retriever: 
Mar 23 19:03:58 net-retriever: gpgv: Signature made Wed Mar 23 15:18:43 2016 UTC using RSA key ID 2B90D010
Mar 23 19:03:58 net-retriever: 
Mar 23 19:03:58 net-retriever: gpgv: Good signature from "Debian Archive Automatic Signing Key (8/jessie) <ftpmaster@debian.org>"
Mar 23 19:03:58 net-retriever: 
**Mar 23 19:03:59 net-retriever: error: main/debian-installer/binary-armel/Packages.xz not found in /tmp/net-retriever-1415-Release (for SHA1 checksum).**
Mar 23 19:04:01 anna[1357]: WARNING **: bad d-i Packages file

It always fails in the step "Download installer components". I tried several different daily builds and around 50 different debian mirrors.

**Comment by rogers0** [comment]
Thanks for trying!

Unfortunately, there's an archive change which debian-installer not supported yet.
The fix is on the way, so please wait a few days.

If you're interested in detail, you can refer the links below.

Announcement:
- https://lists.debian.org/debian-devel-announce/2016/03/msg00006.html
Discussion threads:
- https://lists.debian.org/debian-boot/2016/03/threads.html#00201

**Comment by LPTT** [comment]
I will try to install after easter again

Happy Easter to you and thank you for your work!

**Comment by rogers0** [comment]
Greetings!

Things moves faster than expected, so if you're convenient still, you can try tomorrow's d-i daily.

**Comment by LPTT** [comment]
Hi,

I tried it. Now I can't find a mirror with the right release. Any ideas on that? ;)

 DEBUG: command: wget -q http://lug.mtu.edu/debian/dists/oldstable/Release -O - | grep -E '^(Suite|Codename|Architectures):'
Jan  1 20:25:10 choose-mirror[1623]: DEBUG: command: wget -q http://lug.mtu.edu/debian/dists/stable/Release -O - | grep -E '^(Suite|Codename|Architectures):'
Jan  1 20:25:10 choose-mirror[1623]: DEBUG: command: wget -q http://lug.mtu.edu/debian/dists/testing/Release -O - | grep -E '^(Suite|Codename|Architectures):'
Jan  1 20:25:10 choose-mirror[1623]: DEBUG: command: wget -q http://lug.mtu.edu/debian/dists/unstable/Release -O - | grep -E '^(Suite|Codename|Architectures):'
Jan  1 20:25:10 choose-mirror[1623]: INFO: mirror does not have any suite symlinks
Jan  1 20:25:10 choose-mirror[1623]: DEBUG: command: wget -q http://lug.mtu.edu/debian/dists/stretch/Release -O - | grep -E '^(Suite|Codename|Architectures):'
Jan  1 20:25:10 choose-mirror[1623]: WARNING **: mirror does not support the specified release (stretch)
Jan  1 20:25:15 choose-mirror[1623]: DEBUG: command: wget -q http://ftp.gtlib.gatech.edu/debian/dists/oldstable/Release -O - | grep -E '^(Suite|Codename|Architectures):'
Jan  1 20:25:15 choose-mirror[1623]: DEBUG: command: wget -q http://ftp.gtlib.gatech.edu/debian/dists/stable/Release -O - | grep -E '^(Suite|Codename|Architectures):'
Jan  1 20:25:15 choose-mirror[1623]: DEBUG: command: wget -q http://ftp.gtlib.gatech.edu/debian/dists/testing/Release -O - | grep -E '^(Suite|Codename|Architectures):'
Jan  1 20:25:15 choose-mirror[1623]: DEBUG: command: wget -q http://ftp.gtlib.gatech.edu/debian/dists/unstable/Release -O - | grep -E '^(Suite|Codename|Architectures):'
Jan  1 20:25:15 choose-mirror[1623]: INFO: mirror does not have any suite symlinks
Jan  1 20:25:15 choose-mirror[1623]: DEBUG: command: wget -q http://ftp.gtlib.gatech.edu/debian/dists/stretch/Release -O - | grep -E '^(Suite|Codename|Architectures):'
Jan  1 20:25:15 choose-mirror[1623]: WARNING **: mirror does not support the specified release (stretch)

**Comment by rogers0** [comment]
There're a few cases:
- try another mirror, http://httpredir.debian.org/debian is always a safe bet
- your time is incorrect: "Jan 1 20:25:15"

**Comment by LPTT** [comment]
same result: 
Jan  1 20:55:13 choose-mirror[1513]: DEBUG: command: wget -q http://httpredir.debian.org/debian/dists/oldstable/Release -O - | grep -E '^(Suite|Codename|Architectures):'
Jan  1 20:55:13 choose-mirror[1513]: DEBUG: command: wget -q http://httpredir.debian.org/debian/dists/stable/Release -O - | grep -E '^(Suite|Codename|Architectures):'
Jan  1 20:55:13 choose-mirror[1513]: DEBUG: command: wget -q http://httpredir.debian.org/debian/dists/testing/Release -O - | grep -E '^(Suite|Codename|Architectures):'
Jan  1 20:55:13 choose-mirror[1513]: DEBUG: command: wget -q http://httpredir.debian.org/debian/dists/unstable/Release -O - | grep -E '^(Suite|Codename|Architectures):'
Jan  1 20:55:13 choose-mirror[1513]: INFO: mirror does not have any suite symlinks
Jan  1 20:55:13 choose-mirror[1513]: DEBUG: command: wget -q http://httpredir.debian.org/debian/dists/stretch/Release -O - | grep -E '^(Suite|Codename|Architectures):'
Jan  1 20:55:13 choose-mirror[1513]: WARNING **: mirror does not support the specified release (stretch)


The WXL is complete blank so i guess he doesn't have right time in the installer

**Comment by rogers0** [comment]
May I know which d-i version do you use?

e.g. the latest is Mar. 30:
https://d-i.debian.org/daily-images/armel/20160330-00:14/kirkwood/network-console/buffalo/ls-wxl/

**Comment by LPTT** [comment]
i am using the one from today. Next I will try saturday or sundays version

**Comment by rogers0** [comment]
Last time I tried was version "20160325-00:14".

And yes, there're a few changes lately, I'm just not sure whether it's related:
- https://anonscm.debian.org/cgit/d-i/debian-installer.git/log/

**Comment by LPTT** [comment]
Thank you so much.  version "20160325-00:14" is actually downloading. Will let you know when I am done installing

**Comment by LPTT** [comment]
- installer went through without problems until the wants to make the system bootable. 
syslog:
`
Mar 30 19:04:51 in-target: flash-kernel is already the newest version (3.61).
Mar 30 19:04:51 in-target: 0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Mar 30 19:05:02 in-target: Paketlisten werden gelesen...
Mar 30 19:05:02 in-target: 
Mar 30 19:05:03 in-target: AbhÃ¤ngigkeitsbaum wird aufgebaut....
Mar 30 19:05:05 in-target: 
Mar 30 19:05:05 in-target: Statusinformationen werden eingelesen....
Mar 30 19:05:05 in-target: 
Mar 30 19:05:08 in-target: u-boot-tools is already the newest version (2016.03+dfsg1-1).
Mar 30 19:05:08 in-target: 0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Mar 30 19:05:11 in-target: update-initramfs: Generating /boot/initrd.img-4.4.0-1-marvell
Mar 30 19:05:17 in-target: UUID 112a86a2-3746-4519-85a2-47ef65ef4470 doesn't exist in /dev/disk/by-uuid
Mar 30 19:05:17 in-target: Warning: root device /dev/disk/by-uuid/112a86a2-3746-4519-85a2-47ef65ef4470 does not exist
Mar 30 19:05:17 in-target: 
Mar 30 19:05:17 in-target: Unable to abort; system will probably be broken!
Mar 30 19:05:42 in-target: kirkwood-linkstation: machine: Buffalo Linkstation LS-WXL
Mar 30 19:05:42 in-target: kirkwood-linkstation: Unable to determine Buffalo Linkstation LS-WXL variant 
Mar 30 19:05:42 in-target: dtb-probe /usr/share/flash-kernel/dtb-probe/kirkwood-linkstation failed
Mar 30 19:05:43 flash-kernel-installer: error: flash-kernel failed
Mar 30 19:05:43 main-menu[1253]: WARNING **: Configuring 'flash-kernel-installer' failed with error code 1
Mar 30 19:05:43 main-menu[1253]: WARNING **: Menu item 'flash-kernel-installer' failed.
`

- In the step before "choosing and installing software" I chose web server, print server, ssh-server and standard-systemtools. Should I install any of the other offered things (debian desktop environment, gnome, xfce, kde, cinnamon, mate, lxde)?

**Comment by rogers0** [comment]
It seems due to a change to flash-kernel. Let me look into it.
Thanks for helping to test!

**Comment by rogers0** [comment]
Confirmed it's my fault. Fix is under preparing.
Sorry to inform you that you still wait for a few days...

**Comment by LPTT** [comment]
no problem, I'm happy to test your new version. :)

**Comment by C007dudz** [comment]
Hi rogers0,

For the d-i, is SSH enabled by default? I used Mar25th version last time and I was able to complete the setup but the nas box(ls-wxl) endlessly rebooted. I can't provide any logs as I cannot access the unit as I have not modded it to enable serial (since having a serial console from the unit needs some desoldering).

**Comment by rogers0** [comment]
As posted above, there's a bug in flash-kernel, which still need some time to fix.
Sorry about it.
Please wait for a week or so. I'll keep you posted.

**Comment by rogers0** [comment]
flash-kernel 3.62 hits sid [0], so if you install sid (need to choose advance mode in debian-installer), it should be fine.

But if you want to install stretch (testing), you can wait for another 4 days.
3.62 is scheduled to enter testing on April 11, if no serious bug is found these days.

[0] https://tracker.debian.org/pkg/flash-kernel

**Comment by LPTT** [comment]
Hi rogers0,

I tried the version of today. Install completed successfully but again I'm stuck in bootloop. Any ideas? Is there maybe a way to repair it manually?

**Comment by rogers0** [comment]
I didn't have time to have a test yet.
You can try to check the log before rebooting.
You can make a 2nd ssh connection to the box and choose to enter the shell, then:
- tail -f /var/log/syslog
will show you the log.

**Comment by LPTT** [comment]
That's the last log before hitting Restart. The time is off by 3h.


Apr 13 17:51:58 user-setup: Done.
Apr 13 17:51:59 user-setup: adduser: The group `scanner' does not exist.
Apr 13 17:52:00 user-setup: adduser: The group `bluetooth' does not exist.
Apr 13 17:52:01 user-setup: adduser: The group `debian-tor' does not exist.
Apr 13 17:52:02 user-setup: adduser: The group `lpadmin' does not exist.
Apr 13 17:52:02 finish-install: info: Running /usr/lib/finish-install.d/07preseed
Apr 13 17:52:02 finish-install: info: Running /usr/lib/finish-install.d/07speakup
Apr 13 17:52:02 finish-install: info: Running /usr/lib/finish-install.d/10clock-setup
Apr 13 17:52:02 anna-install: Installing rtc-modules
Apr 13 17:52:02 hw-detect: modprobe: FATAL: Module rtc not found in directory /lib/modules/4.4.0-1-marvell
Apr 13 17:52:02 clock-setup: rtc module not loaded
Apr 13 17:52:02 hw-detect: modprobe: FATAL: Module rtc-dev not found in directory /lib/modules/4.4.0-1-marvell
Apr 13 17:52:02 clock-setup: rtc-dev module not loaded
Apr 13 17:52:03 clock-setup: hwclock from util-linux 2.27.1
Apr 13 17:52:03 clock-setup: Using the /dev interface to the clock.
Apr 13 17:52:03 clock-setup: Assuming hardware clock is kept in UTC time.
Apr 13 17:52:03 clock-setup: Waiting for clock tick...
Apr 13 17:52:03 clock-setup: ...got clock tick
Apr 13 17:52:03 clock-setup: Time read from Hardware Clock: 2016/04/13 17:48:51
Apr 13 17:52:03 clock-setup: Hw clock time : 2016/04/13 17:48:51 = 1460569731 seconds since 1969
Apr 13 17:52:03 clock-setup: Time since last adjustment is 1460569731 seconds
Apr 13 17:52:03 clock-setup: Calculated Hardware Clock drift is 0.000000 seconds
Apr 13 17:52:03 clock-setup: missed it - 1460569922.884893 is too far past 1460569922.500000 (0.384893 > 0.001000)
Apr 13 17:52:03 clock-setup: 1460569923.500000 is close enough to 1460569923.500000 (0.000000 < 0.002000)
Apr 13 17:52:03 clock-setup: Set RTC to 1460569923 (1460569922 + 1; refsystime = 1460569922.000000)
Apr 13 17:52:03 clock-setup: Setting Hardware Clock to 17:52:03 = 1460569923 seconds since 1969
Apr 13 17:52:03 clock-setup: ioctl(RTC_SET_TIME) was successful.
Apr 13 17:52:03 clock-setup: Not adjusting drift factor because the --update-drift option was not used.
Apr 13 17:52:03 finish-install: info: Running /usr/lib/finish-install.d/10update-initramfs
Apr 13 17:52:04 finish-install: info: Running /usr/lib/finish-install.d/20final-message

**Comment by rogers0** [comment]
It's strange that there's no log mention installing flash-kernel package.
Please confirm it's installed, and kernel image is correctly generated.

**Comment by LPTT** [comment]
How can I confirm it? 
On the first partition i have these files 
`-rw-r--r--  1 root root  148948 Mär 17 17:09 config-4.4.0-1-marvell
lrwxrwxrwx  1 root root      51 Apr 13 19:51 dtb -> dtbs/4.4.0-1-marvell/kirkwood-linkstation-lswxl.dtb
lrwxrwxrwx  1 root root      51 Apr 13 19:51 dtb-4.4.0-1-marvell -> dtbs/4.4.0-1-marvell/kirkwood-linkstation-lswxl.dtb
drwxr-xr-x  3 root root    1024 Apr 13 19:51 dtbs
-rw-r--r--  1 root root 3943495 Apr 13 19:51 initrd.buffalo
lrwxrwxrwx  1 root root      26 Apr 13 19:24 initrd.img -> initrd.img-4.4.0-1-marvell
-rw-r--r--  1 root root 3943431 Apr 13 19:51 initrd.img-4.4.0-1-marvell
drwx------  2 root root   12288 Apr 13 19:04 lost+found
-rw-r--r--  1 root root 1650773 Mär 17 17:09 System.map-4.4.0-1-marvell
-rw-r--r--  1 root root 2006009 Apr 13 19:51 uImage.buffalo
lrwxrwxrwx  1 root root      23 Apr 13 19:24 vmlinuz -> vmlinuz-4.4.0-1-marvell
-rw-r--r--  1 root root 1992536 Mär 17 17:08 vmlinuz-4.4.0-1-marvell
`

**Comment by rogers0** [comment]
The file list on 1st partition shows flash-kernel installs OK.
So you're still loops on rebooting?

Did you use RAID-1, keep the original RAID-1 from buffalo, or you created new md device on new HDD?
The first partition must be with metadata 0.90, as described in NEWS part of https://github.com/rogers0/OpenLinkstation

Did you follow the command below?
- mdadm --create /dev/md0 --level=1 --raid-devices=2 -e 0 /dev/sda1 /dev/sdb1

**Comment by rogers0** [comment]
@LPTT
Did you problem get solved?

**Comment by rogers0** [comment]
@LPTT 
Guess your problem get solved. If you meet new problem, please open a new ticket. Thank you!
